#!/bin/sh
#
# (c) 2010, Andrew Johnstone andrew @ajohnstone.com
# Based on the 'proc_mem' plugin, written by Rodrigo Sieiro rsieiro @gmail.com
#
# Configure it by using the processes env var, i.e.:
#
# [proc_mem]
# env.processes        php mysqld apache2
#
 
. $MUNIN_LIBDIR/plugins/plugin.sh
 
if [ "$1" = "autoconf" ]; then
        echo yes
        exit 0
fi
 
processes=${processes:="php mysqld apache2"}
 
if [ "$1" = "config" ]; then
 
        NCPU=$(egrep '^cpu[0-9]+ ' /proc/stat | wc -l)
        PERCENT=$(($NCPU * 100))
        if [ "$scaleto100" = "yes" ]; then
                graphlimit=100
        else
                graphlimit=$PERCENT
        fi
        SYSWARNING=`expr $PERCENT '*' 30 / 100`
        SYSCRITICAL=`expr $PERCENT '*' 50 / 100`
        USRWARNING=`expr $PERCENT '*' 80 / 100`
 
        echo 'graph_title CPU usage by process'
        echo "graph_args --base 1000 -r --lower-limit 0 --upper-limit $graphlimit"
        echo 'graph_vlabel %'
        echo 'graph_category processes'
        echo 'graph_info This graph shows the cpu usage of several processes'
 
        for proc in $processes; do
                  echo "$proc.label $proc"
        done
        exit 0
fi
 
TMPFILE=`mktemp -t top.XXXXXXXXXX` && {
 
  top -b -n1 > $TMPFILE
1chmod 755 /usr/share/munin/plugins/proc_cpu
ln -s /usr/share/munin/plugins/proc_cpu /etc/munin/plugins/pr
  for proc in $processes; do
    value=$(cat $TMPFILE | grep $proc | awk 'BEGIN { SUM = 0 } { SUM += $9} END { print SUM }')
    echo "$proc.value $value"
  done
  rm -f $TMPFILE
}
